name: TOIO
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  fl_chart: ^0.66.2
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  sqflite: ^2.3.2
  animated_floating_buttons: ^0.0.2
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  hexcolor: ^3.0.1
  flutter_slidable: ^3.0.1
  flutter_zoom_drawer: ^3.1.2
  dropdown_button2: ^2.3.9
  day_night_time_picker: ^1.3.0+1
  loading_indicator: ^3.1.1
  get_it: ^7.6.7
  flutter_switch: ^0.3.2
  flutter_native_splash: ^2.3.11
  flutter_styled_toast: ^2.2.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

#launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

#splash
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  android_gravity: center
  android: true
  ios: true
  image: assets/images/app.png



flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

flutter_intl:
  enabled: true
